### ISSUE TITLE
Could you please provide a detailed requirements.txt

### ISSUE THREAD

**Issue by BrandoZhang** [Xharlie/DISN#2]
It can be easily exported via `pip freeze > requirements.txt` if you are using virtual environment.

I get stuck in linking to some dynamic libraries. It seems that I miss some dependencies.

The following is the result I get from `pip freeze > requirements.txt`:

```
bsl-py==0.8.0
astor==0.8.0
backcall==0.1.0
certifi==2019.9.11
decorator==4.4.0
gast==0.3.2
grpcio==1.16.1
h5py==2.8.0
ipykernel==5.1.2
ipython==7.8.0
ipython-genutils==0.2.0
jedi==0.15.1
joblib==0.13.2
jupyter-client==5.3.3
jupyter-core==4.5.0
Markdown==3.1.1
mkl-fft==1.0.14
mkl-random==1.1.0
mkl-service==2.3.0
networkx==2.3
nose==1.3.7
numpy==1.16.5
parso==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
prompt-toolkit==2.0.9
protobuf==3.9.2
ptyprocess==0.6.0
Pygments==2.4.2
pymesh==1.0.2
pymesh2==0.2.1
python-dateutil==2.8.0
pyzmq==18.1.0
scipy==1.3.1
six==1.12.0
tensorboard==1.10.0
tensorflow==1.10.0
termcolor==1.1.0
tornado==6.0.3
traitlets==4.3.2
trimesh==2.37.20
wcwidth==0.1.7
Werkzeug==0.16.0
```

Besides these, I build PyMesh from source code and `conda install -c menpo opencv`.

**Comment by Xharlie** [comment]
Well this is what the command gave me:
absl-py==0.7.1
astor==0.8.0
certifi==2019.6.16
cmake==3.14.4
cycler==0.10.0
decorator==4.4.0
future-fstrings==1.2.0
gast==0.2.2
grpcio==1.16.1
h5py==2.9.0
joblib==0.13.2
kiwisolver==1.1.0
Markdown==3.1.1
matplotlib==3.1.1
mkl-fft==1.0.14
mkl-random==1.1.0
mkl-service==2.3.0
networkx==2.3
numpy==1.16.4
opencv-python==4.1.1.26
protobuf==3.8.0
pymesh2==0.2.1
pyparsing==2.4.2
python-dateutil==2.8.0
scipy==1.3.1
six==1.12.0
style==1.1.0
tensorboard==1.10.0
tensorflow==1.10.0
termcolor==1.1.0
tornado==6.0.3
trimesh==2.37.20
update==0.0.1
Werkzeug==0.15.5



Can you please install whatever the exception indicated. for example, if it shows no joblib, just install joblib.  Also google whatever dynamic library that is incorrectly linked. Add them to your LIB PATH or 
some environment variables.
By doing this, I have never fail to execute any script from internet unless the operating system has some limitations.

**Comment by gokceay** [comment]
> It can be easily exported via `pip freeze > requirements.txt` if you are using virtual environment.
> 
> I get stuck in linking to some dynamic libraries. It seems that I miss some dependencies.
> 
> The following is the result I get from `pip freeze > requirements.txt`:
> 
> ```
> bsl-py==0.8.0
> astor==0.8.0
> backcall==0.1.0
> certifi==2019.9.11
> decorator==4.4.0
> gast==0.3.2
> grpcio==1.16.1
> h5py==2.8.0
> ipykernel==5.1.2
> ipython==7.8.0
> ipython-genutils==0.2.0
> jedi==0.15.1
> joblib==0.13.2
> jupyter-client==5.3.3
> jupyter-core==4.5.0
> Markdown==3.1.1
> mkl-fft==1.0.14
> mkl-random==1.1.0
> mkl-service==2.3.0
> networkx==2.3
> nose==1.3.7
> numpy==1.16.5
> parso==0.5.1
> pexpect==4.7.0
> pickleshare==0.7.5
> prompt-toolkit==2.0.9
> protobuf==3.9.2
> ptyprocess==0.6.0
> Pygments==2.4.2
> pymesh==1.0.2
> pymesh2==0.2.1
> python-dateutil==2.8.0
> pyzmq==18.1.0
> scipy==1.3.1
> six==1.12.0
> tensorboard==1.10.0
> tensorflow==1.10.0
> termcolor==1.1.0
> tornado==6.0.3
> traitlets==4.3.2
> trimesh==2.37.20
> wcwidth==0.1.7
> Werkzeug==0.16.0
> ```
> 
> Besides these, I build PyMesh from source code and `conda install -c menpo opencv`.

Hi Brando, I am having issues building pymesh from source, it strangely gives libtbb.so problem. How did you install from the source? Could you share it with me? Thanks in advance

**Comment by BrandoZhang** [comment]
> > It can be easily exported via `pip freeze > requirements.txt` if you are using virtual environment.
> > I get stuck in linking to some dynamic libraries. It seems that I miss some dependencies.
> > The following is the result I get from `pip freeze > requirements.txt`:
> > ```
> > bsl-py==0.8.0
> > astor==0.8.0
> > backcall==0.1.0
> > certifi==2019.9.11
> > decorator==4.4.0
> > gast==0.3.2
> > grpcio==1.16.1
> > h5py==2.8.0
> > ipykernel==5.1.2
> > ipython==7.8.0
> > ipython-genutils==0.2.0
> > jedi==0.15.1
> > joblib==0.13.2
> > jupyter-client==5.3.3
> > jupyter-core==4.5.0
> > Markdown==3.1.1
> > mkl-fft==1.0.14
> > mkl-random==1.1.0
> > mkl-service==2.3.0
> > networkx==2.3
> > nose==1.3.7
> > numpy==1.16.5
> > parso==0.5.1
> > pexpect==4.7.0
> > pickleshare==0.7.5
> > prompt-toolkit==2.0.9
> > protobuf==3.9.2
> > ptyprocess==0.6.0
> > Pygments==2.4.2
> > pymesh==1.0.2
> > pymesh2==0.2.1
> > python-dateutil==2.8.0
> > pyzmq==18.1.0
> > scipy==1.3.1
> > six==1.12.0
> > tensorboard==1.10.0
> > tensorflow==1.10.0
> > termcolor==1.1.0
> > tornado==6.0.3
> > traitlets==4.3.2
> > trimesh==2.37.20
> > wcwidth==0.1.7
> > Werkzeug==0.16.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Besides these, I build PyMesh from source code and `conda install -c menpo opencv`.
> 
> Hi Brando, I am having issues building pymesh from source, it strangely gives libtbb.so problem. How did you install from the source? Could you share it with me? Thanks in advance

Hi Gokce, I just followed the [PyMesh README](https://github.com/PyMesh/PyMesh) to build from source. I noticed that PyMesh hasn't updated for 4 years, which may have some broken dependencies. Hope this helps.

**Comment by gokceay** [comment]
> > > It can be easily exported via `pip freeze > requirements.txt` if you are using virtual environment.
> > > I get stuck in linking to some dynamic libraries. It seems that I miss some dependencies.
> > > The following is the result I get from `pip freeze > requirements.txt`:
> > > ```
> > > bsl-py==0.8.0
> > > astor==0.8.0
> > > backcall==0.1.0
> > > certifi==2019.9.11
> > > decorator==4.4.0
> > > gast==0.3.2
> > > grpcio==1.16.1
> > > h5py==2.8.0
> > > ipykernel==5.1.2
> > > ipython==7.8.0
> > > ipython-genutils==0.2.0
> > > jedi==0.15.1
> > > joblib==0.13.2
> > > jupyter-client==5.3.3
> > > jupyter-core==4.5.0
> > > Markdown==3.1.1
> > > mkl-fft==1.0.14
> > > mkl-random==1.1.0
> > > mkl-service==2.3.0
> > > networkx==2.3
> > > nose==1.3.7
> > > numpy==1.16.5
> > > parso==0.5.1
> > > pexpect==4.7.0
> > > pickleshare==0.7.5
> > > prompt-toolkit==2.0.9
> > > protobuf==3.9.2
> > > ptyprocess==0.6.0
> > > Pygments==2.4.2
> > > pymesh==1.0.2
> > > pymesh2==0.2.1
> > > python-dateutil==2.8.0
> > > pyzmq==18.1.0
> > > scipy==1.3.1
> > > six==1.12.0
> > > tensorboard==1.10.0
> > > tensorflow==1.10.0
> > > termcolor==1.1.0
> > > tornado==6.0.3
> > > traitlets==4.3.2
> > > trimesh==2.37.20
> > > wcwidth==0.1.7
> > > Werkzeug==0.16.0
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Besides these, I build PyMesh from source code and `conda install -c menpo opencv`.
> > 
> > 
> > Hi Brando, I am having issues building pymesh from source, it strangely gives libtbb.so problem. How did you install from the source? Could you share it with me? Thanks in advance
> 
> Hi Gokce, I just followed the [PyMesh README](https://github.com/PyMesh/PyMesh) to build from source. I noticed that PyMesh hasn't updated for 4 years, which may have some broken dependencies. Hope this helps.

thanks a lot for your quick response, I will try from the link you shared
