### ISSUE TITLE
There is no corresponding placeholder in the checkpoint for new version cam model.

### ISSUE THREAD

**Issue by walsvid** [Xharlie/DISN#4]
Thank you very much for providing the code.

I downloaded the checkpoint file from the google drive link, but when I executed the demo script. The code raise an error, there is no placeholder called `norm_params_pl` for this [line](https://github.com/Xharlie/DISN/blob/8955ed9dbe464e4233e1da5366a54e72e7b371ae/cam_est/model_cam.py#L24) of code. 

When I using the old version code from [https://github.com/laughtervv/DISN](https://github.com/laughtervv/DISN), it is correct. I wonder will you to update the checkpoint file?

**Comment by Xharlie** [comment]
thank you for reporting the bug. i bandaged it with a old model file in the cam_est folder. Since we added a new dataset, the cam model file changed a bit.

**Comment by walsvid** [comment]
Hi, thank you for your reply. I update the code and running demo. But I found the result mesh with estimate camera pose seems worse than the old model? Is it a bug?

**Comment by Xharlie** [comment]
forgot to add another old file, should be fine this time
![Screenshot from 2019-10-17 13-58-11](https://user-images.githubusercontent.com/7820448/67046993-3abb2b80-f0e6-11e9-8413-8b345728f0bf.png)
