### ISSUE TITLE
Am I doing something wrong?

### ISSUE THREAD

**Issue by edoRemelli** [Xharlie/DISN#7]
Thanks for the sharing this with the community!

Should we except a slight misalignment between sdfs in "sdf_dir" and marching cube reconstructed ground truth models in "norm_mesh_dir"?

If I project sdf surface samples (obtained as `np.abs(pc_sdf_sample[:,3])<0.005`) and mesh vertices on the renders using
`trans_mat = np.linalg.multi_dot([K, RT, rot_mat, W2O_mat, norm_mat])`
I notice a slight misalignment for the mesh vertices (see second attached screenshot). 

Is this expected, or am I missing out something? Thanks!!

![image](https://user-images.githubusercontent.com/22614528/75110591-37a1f000-5630-11ea-8ba5-60433dd8625a.png)

![image](https://user-images.githubusercontent.com/22614528/75110594-3d97d100-5630-11ea-8224-4d0ebb8f4cf7.png)

**Comment by bharadwajdhornala** [comment]
Hi @edoRemelli Could you help me solve Issue #6 ?
Thanks!!

**Comment by Xharlie** [comment]
the

**Comment by Xharlie** [comment]
we will actively look at this, does it happen to all the models?

**Comment by zzilch** [comment]
The model was normalized with the center and scale of the sampled points on the surface using trimesh.
However, the sample points are different each time we run the `get_normalize_mesh`.
That might make the `norm_param` not perfectly aligned with the original model.
