### ISSUE TITLE
libtbb_preview.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Hydrogenion** [Xharlie/DISN#8]
When I try to use ./isosurface/computeMarchingCubes or generate SDF data
I got this error:
error while loading shared libraries: libtbb_preview.so.2: cannot open shared object file: No such file or directory

I have already install libtbb, and I can fid libtbb.so.2. But how do you get **libtbb_preview.so.2?**

Thanks!

**Comment by Xharlie** [comment]
just fixed!

**Comment by yigepingzi** [comment]
> just fixed!

May I know how you fixed it?

**Comment by zhang-0515** [comment]
我想请问这个问题解决了吗？我现在也是属于这种情况

**Comment by yigepingzi** [comment]
I used source LIB_PATH. the problem gone

**Comment by zhang-0515** [comment]
![1](https://user-images.githubusercontent.com/72601089/156912387-bb381aa9-0e2c-48a7-883a-caa14da8deab.jpg)
是修改了这里的mkl的位置吗？

**Comment by zhang-0515** [comment]
你下载的mkl可以分享我一份吗？我这里下载的有些许的不对
